[compiler.solc]
include_paths = [
    "node_modules",
]
via_IR = true
exclude_paths = [
    "node_modules",
    ".woke-build",
    "venv",
    "lib",
]

[compiler.solc.optimizer]
enabled = true
runs = 200

[detectors]
exclude = []
exclude_paths = [
    "source/node_modules",
    ".woke-build",
    "venv",
    "lib",
]

[testing]
cmd = "anvil"

[testing.anvil]
cmd_args = "--accounts 100 --prune-history 100 --transaction-block-keeper 10 --steps-tracing --silent"

[testing.ganache]
cmd_args = "-k istanbul -q"

[testing.hardhat]
cmd_args = ""
